### ISSUE TITLE
`./manage.py migrate` failing with "No module named 'debug_toolbar'"

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#112]
Trying to run `./manage.py migrate` in a Dockerized dandi-api instance currently (as of the image built at 2021-02-12T19:05:17.982408398Z) fails with:

```
Traceback (most recent call last):   
  File "./manage.py", line 20, in <module>
    main()
  File "./manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'
```

**Comment by yarikoptic** [comment]
That brakes testing of dandi-cli - having it assessed asap would be greatly appreciated

**Comment by yarikoptic** [comment]
is it just a matter of adding `django-debug-toolbar` to dependencies?

**Comment by brianhelba** [comment]
I think you probably didn't install the project with the `[dev]` extra.

**Comment by dchiquito** [comment]
I didn't know this, but `pip install -e .[extra]` is apparently a valid install command.

**Comment by jwodder** [comment]
Note that I am using the Docker image built from [this Dockerfile](https://github.com/dandi/dandi-api/blob/master/dev/django-public.Dockerfile), so if the install command needs to be modifier, that's where to do it.
