### ISSUE TITLE
error running manage.py

### ISSUE THREAD

**Issue by djarecka** [dandi/dandi-api#534]
I had issues running `docker-compose up` so tried to repeat initial setup starting from `docker-compose run --rm django ./manage.py migrate` and got errors:

```
Creating dandi-api_django_run ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/django-project/dandiapi/api/views/__init__.py", line 1, in <module>
    from .asset import AssetViewSet, asset_download_view, asset_metadata_view
  File "/opt/django-project/dandiapi/api/views/asset.py", line 29, in <module>
    from dandiapi.api.tasks import validate_asset_metadata, validate_version_metadata
  File "/opt/django-project/dandiapi/api/tasks.py", line 27, in <module>
    import dandischema.exceptions
ModuleNotFoundError: No module named 'dandischema.exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    main()
  File "./manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/checks.py", line 9, in pagination_system_check
    if api_settings.PAGE_SIZE and not api_settings.DEFAULT_PAGINATION_CLASS:
  File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'dandiapi.api.views.common.DandiPagination' for API setting 'DEFAULT_PAGINATION_CLASS'. ModuleNotFoundError: No module named 'dandischema.exceptions'.
```

any idea what is wrong?

**Comment by waxlamp** [comment]
attn @dchiquito

**Comment by dchiquito** [comment]
Running `docker-compose build` to rebuild the `django` image and reinstall the `dandischema` dependency solved the problem.
