### ISSUE TITLE
"aged enough" assets are missing SHA256

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#672]
<details>
<summary>our dataladification script errored out </summary> 

```shell
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-1912/sub-1912_obj-2ek7c8_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2019-03-20/sub-X2019-03-20_obj-6ws9hu_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2019-03-20/sub-X2019-03-20_obj-81om7t_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2020-01-06/sub-X2020-01-06_obj-5igldv_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2020-01-06/sub-X2020-01-06_obj-hmr8h6_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2019-03-20/sub-X2019-03-20_obj-r34ix_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2020-01-06/sub-X2020-01-06_obj-g8k1iy_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2019-03-20/sub-X2019-03-20_obj-yg12gj_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2019-03-20/sub-X2019-03-20_obj-10qq1mi_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2019-03-20/sub-X2019-03-20_obj-20785b_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2019-03-20/sub-X2019-03-20_obj-1b325zv_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2020-01-06/sub-X2020-01-06_obj-1597ryw_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2020-01-06/sub-X2020-01-06_obj-1nokg5g_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2020-01-06/sub-X2020-01-06_obj-1t1hms3_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2016-02-25/sub-X2016-02-25_obj-18to69u_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2016-02-25/sub-X2016-02-25_obj-1iczavk_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2016-02-25/sub-X2016-02-25_obj-1y5ham8_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-1803/sub-1803_obj-1s5us30_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-1803/sub-1803_obj-1mtrqka_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:02-0500 [ERROR   ] backups2datalad sub-X2016-02-25/sub-X2016-02-25_obj-qnjj9t_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
...
2022-01-07T09:46:05-0500 [ERROR   ] backups2datalad sub-X2016-02-29/sub-X2016-02-29_obj-19jpiq_icephys.nwb: Asset created more than a day ago but SHA256 digest has not yet been computed
2022-01-07T09:46:05-0500 [ERROR   ] backups2datalad Operation failed with exception:
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/util.py", line 295, in dandi_logging
    yield logfile
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 141, in sync_dataset
    syncer.sync_assets()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/syncer.py", line 44, in sync_assets
    self.report.check()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/util.py", line 116, in check
    raise RuntimeError(
RuntimeError: Errors occurred while downloading: 99 assets on server had no SHA256 hash despite advanced age

```
</details>

and that was on 000211 . Checked for a sample asset in swagger, and 

<details>
<summary>indeed no sha256: </summary> 

```shell
$> curl -s -X GET "https://api.dandiarchive.org/api/assets/bbb22bb0-c560-4079-b2e6-8a8c06b6fd52/" -H "accept: application/json" | jq .
{
  "id": "dandiasset:bbb22bb0-c560-4079-b2e6-8a8c06b6fd52",
  "path": "sub-1912/sub-1912_obj-2ek7c8_icephys.nwb",
  "access": [
    {
      "status": "dandi:OpenAccess",
      "schemaKey": "AccessRequirements"
    }
  ],
  "digest": {
    "dandi:dandi-etag": "880a76da49873fcad37b352d0075d252-1"
  },
  "@context": "https://raw.githubusercontent.com/dandi/schema/master/releases/0.6.0/context.json",
  "approach": [],
  "schemaKey": "Asset",
  "contentUrl": [
    "https://api.dandiarchive.org/api/assets/bbb22bb0-c560-4079-b2e6-8a8c06b6fd52/download/",
    "https://dandiarchive.s3.amazonaws.com/blobs/520/5bf/5205bf12-f7d4-4177-bb3d-d30f851d2bcf"
  ],
  "identifier": "bbb22bb0-c560-4079-b2e6-8a8c06b6fd52",
  "repository": "https://dandiarchive.org/",
  "contentSize": 1422447,
  "dateModified": "2021-12-24T13:27:03.266587-05:00",
  "schemaVersion": "0.6.0",
  "encodingFormat": "application/x-nwb",
  "wasGeneratedBy": [
    {
      "name": "PLACEHOLDER",
      "schemaKey": "Session",
      "startDate": "2019-11-04T15:32:03.343000-05:00",
      "identifier": "PLACEHOLDER",
      "description": "PLACEHOLDER"
    },
    {
      "id": "urn:uuid:74f4c990-0db4-4cf8-acbb-652c5632258a",
      "name": "Metadata generation",
      "schemaKey": "Activity",
      "description": "Metadata generated by DANDI cli",
      "wasAssociatedWith": [
        {
          "url": "https://github.com/dandi/dandi-cli",
          "name": "DANDI Command Line Interface",
          "version": "0.32.2",
          "schemaKey": "Software",
          "identifier": "RRID:SCR_019009"
        }
      ]
    }
  ],
  "wasAttributedTo": [
    {
      "age": {
        "value": "P59Y",
        "unitText": "ISO-8601 duration",
        "schemaKey": "PropertyValue",
        "valueReference": {
          "value": "dandi:BirthReference",
          "schemaKey": "PropertyValue"
        }
      },
      "species": {
        "name": "Human",
        "schemaKey": "SpeciesType",
        "identifier": "http://purl.obolibrary.org/obo/NCBITaxon_9606"
      },
      "schemaKey": "Participant",
      "identifier": "1912"
    }
  ],
  "blobDateModified": "2021-12-24T12:12:09.987594-05:00",
  "variableMeasured": [],
  "measurementTechnique": []
}

```
</details>
and I do not see such assets being listed on dashboard https://api.dandiarchive.org/dashboard/ -- might be worth adding a check? (e.g. if asset older than a day - must have sha256)

**Comment by dchiquito** [comment]
I see that asset `bbb22bb0-c560-4079-b2e6-8a8c06b6fd52` has a sha256 calculated in the DB. I assume the relevant bit of your query is the `digest` field:
```
  "digest": {
    "dandi:dandi-etag": "880a76da49873fcad37b352d0075d252-1"
    # There should be a dandi:sha2-256 right here, but it is absent
  },
```
I will see if there is anything in papertrail.

**Comment by dchiquito** [comment]
It appears that `bbb22bb0-c560-4079-b2e6-8a8c06b6fd52` was the only asset which had not recorded it's sha256 in the metadata. I forcibly saved it to resolve the error.
There was nothing in papertrail indicating a problem with that asset. I assume it was created some time ago.

**Comment by yarikoptic** [comment]
what was not the only asset, there was 99 in total (please expand the first collapse) which lead for that dandiset datalad dataset update fail.  Can there be a utility for dashboard which would find all such assets with sha256 known to DB but not present in metadata records? (ideally only the ones which are referenced somewhere in dandiset versions)

**Comment by dchiquito** [comment]
I just checked again, and according to this query there are no such assets with no sha256 set in the metadata:
```
>>> Asset.objects.filter(~Q(metadata__digest__has_key='dandi:sha2-256')).count()
SELECT COUNT(*) AS "__count"
  FROM "api_asset"
 WHERE NOT (("api_asset"."metadata" -> 'digest') ? 'dandi:sha2-256')

Execution time: 0.254277s [Database: default]
0
>>>
```
Similar results when searching for a sha256 field that is null or is the empty string. Since this query isn't returning anything, it wouldn't be very useful to have on the dashboard.

Do you have IDs of these problematic assets so I can see exactly what's wrong with them?

**Comment by yarikoptic** [comment]
I have done `dandi ls -f json_pp --metadata assets -r dandi://dandi/000211 | jq '.[].metadata.digest."dandi:sha2-256"'` and no empty lines (besides first record for dandiset) were reported.  So, something was odd with our dataladification script (not very likely) or may be some jobs were still running computing sha256s .  ATM it seems to be ok, so let's assume it is all fixed.  I will reopen if I run into the same situation again
