### ISSUE TITLE
needed: more informative error upon asset validation failure than just 500

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#98]
I guess it is just another manifestation of #94 where in #94 it is validation failing at dandiset level, while here it is failing at asset level.

500 error received from the server provides no further information of what kind internal error it is, that it is validation that failed.  Ideally it should return more information on how/why validation failed.

<details>
<summary>the protocol of an attempt on 000007</summary> 

```shell
drogon:/mnt/backup/dandi/dandisets/000007
*$> DANDI_DEVEL=1 dandi --pdb upload -i dandi-api --devel-debug --validation skip sub-anm00314746/sub-anm00314746_ses-20151020T093604.nwb
2021-02-09 15:05:19,974 [    INFO] Found 1 files to consider
{'size': 1388640}
{'status': 'digesting'}
{'status': 'extracting metadata'}
{'status': 'uploading'}
{'status': 'uploading', 'upload': 100.0, 'current': 1388640}
2021-02-09 15:05:21,583 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210209200517Z-32386.log
Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/dandi-devel/bin/dandi", line 33, in <module>
    sys.exit(load_entry_point('dandi', 'console_scripts', 'dandi')())
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/base.py", line 110, in wrapper
    return f(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/cmd_upload.py", line 98, in upload
    upload(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 50, in upload
    return _new_upload(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 869, in _new_upload
    for v in process_path(path, relpath):
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 812, in process_path
    for r in client.iter_upload(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/dandiapi.py", line 451, in iter_upload
    self.post(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/dandiapi.py", line 185, in post
    return self.send_request(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/dandiapi.py", line 149, in send_request
    raise requests.HTTPError(msg, response=result)
requests.exceptions.HTTPError: Error 500 while sending POST request to https://api.dandiarchive.org/api/uploads/validate/

> /home/yoh/proj/dandi/dandi-cli/dandi/dandiapi.py(149)send_request()
-> raise requests.HTTPError(msg, response=result)
(Pdb) l
144
145             # If success, return the json object. Otherwise throw an exception.
146             if not result.ok:
147                 msg = f"Error {result.status_code} while sending {method} request to {url}"
148                 lgr.debug(f"{msg}: {result.text}")
149  ->             raise requests.HTTPError(msg, response=result)
150
151             if json_resp:
152                 if result.text.strip():
153                     return result.json()
154                 else:
(Pdb) p result.content
b'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n'
(Pdb) p result.text
'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n'

```
</details>

**Comment by yarikoptic** [comment]
same for 00008 (see https://github.com/dandi/dandi-api-datasets/issues/7)

**Comment by yarikoptic** [comment]
@mgrauer helped me to navigate to the papertrail logs, apparently it is not per se "validation" (as of metadata to follow the schema) failure but rather something exceeding what DB schema allows

<details>
<summary>full traceback dump... I think there is no pragmatically sensitive data here</summary> 

```
Feb 15 12:49:07 dandi-api heroku/router at=info method=GET path="/api/dandisets/000008/versions/draft/assets/?path=sub-mouse-AAYYT%2Fsub-mouse-AAYYT_ses-20180420-sample-2_slice-20180420-slice-2_cell-20180420-sample-2_icephys.nwb" host=api.dandiarchive.org request_id=66fd2978-f8a5-49eb-9758-1dcc6266f1c4 fwd="129.170.233.10" dyno=web.1 connect=0ms service=81ms status=200 bytes=398 protocol=https
Feb 15 12:49:07 dandi-api app/web.1 10.7.236.68 - - [15/Feb/2021:20:49:07 +0000] "GET /api/dandisets/000008/versions/draft/assets/?path=sub-mouse-AAYYT%2Fsub-mouse-AAYYT_ses-20180420-sample-2_slice-20180420-slice-2_cell-20180420-sample-2_icephys.nwb HTTP/1.1" 200 52 "-" "python-requests/2.23.0"
Feb 15 12:49:07 dandi-api heroku/router at=info method=POST path="/api/uploads/validate/" host=api.dandiarchive.org request_id=515daf3a-1f9c-45b2-8fd2-249b339d3ebe fwd="129.170.233.10" dyno=web.1 connect=0ms service=46ms status=400 bytes=409 protocol=https
Feb 15 12:49:07 dandi-api app/web.1 [20:49:07] WARNING  Bad Request: /api/uploads/validate/               log.py:224
Feb 15 12:49:07 dandi-api app/web.1 10.79.224.171 - - [15/Feb/2021:20:49:07 +0000] "POST /api/uploads/validate/ HTTP/1.1" 400 65 "-" "python-requests/2.23.0"
Feb 15 12:49:08 dandi-api app/web.1 10.7.164.30 - - [15/Feb/2021:20:49:07 +0000] "POST /api/uploads/initialize/ HTTP/1.1" 200 1030 "-" "python-requests/2.23.0"
Feb 15 12:49:08 dandi-api heroku/router at=info method=POST path="/api/uploads/initialize/" host=api.dandiarchive.org request_id=66cafcb1-2f94-451f-a760-71782f3b72d5 fwd="129.170.233.10" dyno=web.1 connect=1ms service=141ms status=200 bytes=1367 protocol=https
Feb 15 12:49:08 dandi-api heroku/router at=info method=POST path="/api/uploads/complete/" host=api.dandiarchive.org request_id=4063de56-b34c-419a-8947-d927d37b30f8 fwd="129.170.233.10" dyno=web.1 connect=0ms service=26ms status=200 bytes=1216 protocol=https
Feb 15 12:49:09 dandi-api app/web.1 10.186.202.203 - - [15/Feb/2021:20:49:08 +0000] "POST /api/uploads/complete/ HTTP/1.1" 200 880 "-" "python-requests/2.23.0"
Feb 15 12:49:09 dandi-api heroku/router at=info method=POST path="/api/uploads/validate/" host=api.dandiarchive.org request_id=1d08f582-5bcb-4896-a420-adbf4a4055fc fwd="129.170.233.10" dyno=web.1 connect=1ms service=361ms status=500 bytes=463 protocol=https
Feb 15 12:49:09 dandi-api app/web.1 [20:49:09] ERROR    Internal Server Error: /api/uploads/validate/     log.py:224
Feb 15 12:49:09 dandi-api app/web.1                     Traceback (most recent call last):                          
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/backends/utils.py", line 84, in            
Feb 15 12:49:09 dandi-api app/web.1                     _execute                                                    
Feb 15 12:49:09 dandi-api app/web.1                         return self.cursor.execute(sql, params)                 
Feb 15 12:49:09 dandi-api app/web.1                     psycopg2.errors.StringDataRightTruncation: value            
Feb 15 12:49:09 dandi-api app/web.1                     too long for type character varying(100)                    
Feb 15 12:49:09 dandi-api app/web.1                     The above exception was the direct cause of the             
Feb 15 12:49:09 dandi-api app/web.1                     following exception:                                        
Feb 15 12:49:09 dandi-api app/web.1                     Traceback (most recent call last):                          
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/core/handlers/exception.py", line             
Feb 15 12:49:09 dandi-api app/web.1                     47, in inner                                                
Feb 15 12:49:09 dandi-api app/web.1                         response = get_response(request)                        
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/core/handlers/base.py", line 181,             
Feb 15 12:49:09 dandi-api app/web.1                     in _get_response                                            
Feb 15 12:49:09 dandi-api app/web.1                         response = wrapped_callback(request,                    
Feb 15 12:49:09 dandi-api app/web.1                     *callback_args, **callback_kwargs)                          
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/sentry_sdk/integrations/django/views.py",            
Feb 15 12:49:09 dandi-api app/web.1                     line 67, in sentry_wrapped_callback                         
Feb 15 12:49:09 dandi-api app/web.1                         return callback(request, *args, **kwargs)               
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/views/decorators/csrf.py", line 54,           
Feb 15 12:49:09 dandi-api app/web.1                     in wrapped_view                                             
Feb 15 12:49:09 dandi-api app/web.1                         return view_func(*args, **kwargs)                       
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/views/generic/base.py", line 70, in           
Feb 15 12:49:09 dandi-api app/web.1                     view                                                        
Feb 15 12:49:09 dandi-api app/web.1                         return self.dispatch(request, *args,                    
Feb 15 12:49:09 dandi-api app/web.1                     **kwargs)                                                   
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/rest_framework/views.py", line 509, in               
Feb 15 12:49:09 dandi-api app/web.1                     dispatch                                                    
Feb 15 12:49:09 dandi-api app/web.1                         response = self.handle_exception(exc)                   
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/rest_framework/views.py", line 469, in               
Feb 15 12:49:09 dandi-api app/web.1                     handle_exception                                            
Feb 15 12:49:09 dandi-api app/web.1                         self.raise_uncaught_exception(exc)                      
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/rest_framework/views.py", line 480, in               
Feb 15 12:49:09 dandi-api app/web.1                     raise_uncaught_exception                                    
Feb 15 12:49:09 dandi-api app/web.1                         raise exc                                               
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/rest_framework/views.py", line 506, in               
Feb 15 12:49:09 dandi-api app/web.1                     dispatch                                                    
Feb 15 12:49:09 dandi-api app/web.1                         response = handler(request, *args, **kwargs)            
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/rest_framework/decorators.py", line 50, in           
Feb 15 12:49:09 dandi-api app/web.1                     handler                                                     
Feb 15 12:49:09 dandi-api app/web.1                         return func(*args, **kwargs)                            
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/dandiapi/api/views/upload.py", line            
Feb 15 12:49:09 dandi-api app/web.1                     191, in upload_validate_view                                
Feb 15 12:49:09 dandi-api app/web.1                         validation.save()                                       
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django_extensions/db/models.py", line 22,            
Feb 15 12:49:09 dandi-api app/web.1                     in save                                                     
Feb 15 12:49:09 dandi-api app/web.1                         super().save(**kwargs)                                  
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/models/base.py", line 753, in              
Feb 15 12:49:09 dandi-api app/web.1                     save                                                        
Feb 15 12:49:09 dandi-api app/web.1                         self.save_base(using=using,                             
Feb 15 12:49:09 dandi-api app/web.1                     force_insert=force_insert,                                  
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/models/base.py", line 790, in              
Feb 15 12:49:09 dandi-api app/web.1                     save_base                                                   
Feb 15 12:49:09 dandi-api app/web.1                         updated = self._save_table(                             
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/models/base.py", line 895, in              
Feb 15 12:49:09 dandi-api app/web.1                     _save_table                                                 
Feb 15 12:49:09 dandi-api app/web.1                         results = self._do_insert(cls._base_manager,            
Feb 15 12:49:09 dandi-api app/web.1                     using, fields, returning_fields, raw)                       
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/models/base.py", line 933, in              
Feb 15 12:49:09 dandi-api app/web.1                     _do_insert                                                  
Feb 15 12:49:09 dandi-api app/web.1                         return manager._insert(                                 
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/models/manager.py", line 85, in            
Feb 15 12:49:09 dandi-api app/web.1                     manager_method                                              
Feb 15 12:49:09 dandi-api app/web.1                         return getattr(self.get_queryset(),                     
Feb 15 12:49:09 dandi-api app/web.1                     name)(*args, **kwargs)                                      
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/models/query.py", line 1254, in            
Feb 15 12:49:09 dandi-api app/web.1                     _insert                                                     
Feb 15 12:49:09 dandi-api app/web.1                         return query.get_compiler(using=using).execut           
Feb 15 12:49:09 dandi-api app/web.1                     e_sql(returning_fields)                                     
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/models/sql/compiler.py", line              
Feb 15 12:49:09 dandi-api app/web.1                     1397, in execute_sql                                        
Feb 15 12:49:09 dandi-api app/web.1                         cursor.execute(sql, params)                             
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/sentry_sdk/integrations/django/__init__.py           
Feb 15 12:49:09 dandi-api app/web.1                     ", line 493, in execute                                     
Feb 15 12:49:09 dandi-api app/web.1                         return real_execute(self, sql, params)                  
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/backends/utils.py", line 66, in            
Feb 15 12:49:09 dandi-api app/web.1                     execute                                                     
Feb 15 12:49:09 dandi-api app/web.1                         return self._execute_with_wrappers(sql,                 
Feb 15 12:49:09 dandi-api app/web.1                     params, many=False, executor=self._execute)                 
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/backends/utils.py", line 75, in            
Feb 15 12:49:09 dandi-api app/web.1                     _execute_with_wrappers                                      
Feb 15 12:49:09 dandi-api app/web.1                         return executor(sql, params, many, context)             
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/backends/utils.py", line 84, in            
Feb 15 12:49:09 dandi-api app/web.1                     _execute                                                    
Feb 15 12:49:09 dandi-api app/web.1                         return self.cursor.execute(sql, params)                 
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/utils.py", line 90, in __exit__            
Feb 15 12:49:09 dandi-api app/web.1                         raise dj_exc_value.with_traceback(traceback)            
Feb 15 12:49:09 dandi-api app/web.1                     from exc_value                                              
Feb 15 12:49:09 dandi-api app/web.1                       File "/app/.heroku/python/lib/python3.8/site-pa           
Feb 15 12:49:09 dandi-api app/web.1                     ckages/django/db/backends/utils.py", line 84, in            
Feb 15 12:49:09 dandi-api app/web.1                     _execute                                                    
Feb 15 12:49:09 dandi-api app/web.1                         return self.cursor.execute(sql, params)                 
Feb 15 12:49:09 dandi-api app/web.1                     django.db.utils.DataError: value too long for               
Feb 15 12:49:09 dandi-api app/web.1                     type character varying(100)                                 
Feb 15 12:49:09 dandi-api app/web.1 10.30.238.92 - - [15/Feb/2021:20:49:09 +0000] "POST /api/uploads/validate/ HTTP/1.1" 500 145 "-" "python-requests/2.23.0"
```
</details>

**Comment by yarikoptic** [comment]
from quick investigation/ideas from @mgrauer:

```
Michael Grauer  4 minutes ago
my guess is it is on the object_key field

Yarik  3 minutes ago
or may be path? :wink:

Michael Grauer  2 minutes ago
this is 161 chars

Michael Grauer  2 minutes ago
000008/draft/sub-mouse-AAYYT/sub-mouse-AAYYT_ses-20180420-sample-3_slice-20180420-slice-3_cell-20180420-sample-3_icephys.nwb/0b996edf-bc96-4758-904a-87b70ad7b392

Michael Grauer  2 minutes ago
i don't know if we should set a limit, but there is a lot of repeated info in that key

Yarik  < 1 minute ago
oh -- that is probably result from https://github.com/dandi/dandi-api/pull/84 which hopefully would get properly addressed by https://github.com/dandi/dandi-api/pull/104
```

**Comment by dchiquito** [comment]
This issue should indeed be addressed by #104. We could extend the size of the column, but I don't think it's necessary considering that soon everything we store will be less than 100 characters.

**Comment by yarikoptic** [comment]
It would indeed address #114 but I wonder if there should be additional guarding and know informative messages for 500 in general (at least may be type of exception caught if not full str to not potentially leak sensitive data)

**Comment by waxlamp** [comment]
> It would indeed address #114 but I wonder if there should be additional guarding and know informative messages for 500 in general (at least may be type of exception caught if not full str to not potentially leak sensitive data)

I agree this would be a good idea. It seems like the best way to handle this would be to encounter a 500 error, file an issue describing the actions that led to that error, and then investigate how to improve the error message for that case. We can also do this prophylactically, if we know of specific places where a better error message is warranted. But I don't think it's optimally productive to keep a long-running issue open until all such cases are found and fixed. We could even have a GitHub label specific to error message improvement, in case we want to do some analysis or organization of these issues as they come up.

What do you think, @yarikoptic?

**Comment by yarikoptic** [comment]
> But I don't think it's optimally productive to keep a long-running issue open until all such cases are found and fixed. We could even have a GitHub label specific to error message improvement, in case we want to do some analysis or organization of these issues as they come up.

This particular issue is about improving the error message, it is not about identifying all cases.  For the particular case I filed e.g. #114, which was addressed/closed.  If we/you decide that error message should **not** be improved -- could be closed (ideally a label "wontfix" or alike added) without resolution.  If we think that it is worthwhile, could be labeled as "severity-wishlist" or a like, but I `[*]` would prefer to keep such issues open until they are either decided not to act upon (so "wontfix" from before) due to e.g. long time elapsed without demand voiced, or properly resolved/closed.  Hope it makes sense, but I am open to alternatives ;)  

`[*]` yeap, in datalad we do have 695 open issues, but many more closed ;)

**Comment by waxlamp** [comment]
I see where you're coming from, @yarikoptic. But I think this specific issue is non-actionable because the error message you encountered is a generic fallback message that occurs when that error condition isn't properly handled by some other logic. In this case, it turned out to be a specific bug where a long filename clashed with a Django varchar field, etc., so the condition that led to this unhandled error has been made impossible in future execution.

Therefore, I don't think there's anything to improve about this error message--by the time this error message is generated, there cannot, by definition, be any extra information to report, and thus nothing to change. Essentially, this is a message Django generates when the app has failed to catch and process the error condition.

Let me know if there's anything about the situation that I've mischaracterized or otherwise missed. I want to make sure we're not talking past each other on this 🗣️

**Comment by yarikoptic** [comment]
unfortunately I do not have enough (well -- any) django-foo to recommend a specific solution, but I would expect possible having some `@handle_error` decorator around endpoints which would return a more informative error should be a possibility if there is no a better django way (e.g. may be something along [those instrumentations](https://docs.djangoproject.com/en/3.1/howto/error-reporting/))

**Comment by waxlamp** [comment]
I believe we _can_ supply better error messages for specific error conditions, at the points where those conditions are detected, but that is a general approach to error messages that is not covered by this issue.

I think you might be asking for fallback error messages per endpoint that can mention, e.g., that endpoint or something like that. But since we have access to the tracebacks in the logs, which in turn indicate which endpoint precipitated the error, I'm not sure we need to do anything like that.

I'm on the verge of closing this as `wontfix` but that's because I really don't believe this is actionable. If you can clarify with an example of what you'd like to see in the API that would solve this issue, that would help me understand what to do.

**Comment by yarikoptic** [comment]
re example -- see original issue example - user received a non-informative "Error 500 while sending POST request to https://api.dandiarchive.org/api/uploads/validate/" . We do have a datestamp - 20210209200517Z (so not that long ago, unlike could be longer in real-life). Can you tell quickly now even if at some high level what server side issue has caused that 500 and either it is something what might have been addressed already or not?

**Comment by dchiquito** [comment]
The timestamp can easily be used to search for the error logged in Papertrail, which should give a stack trace and contain more interesting information about the error. The stack trace can be used to check Sentry, which provides a more holistic view of the context of the error.

**Comment by yarikoptic** [comment]
sure, but "can easily" is not exactly the answer to my specific question ("..what server side issue has caused that 500...?") and that is my point... it would take time to open the page, search for properly formatted date time (hopefully for the correct zone).

Not that ability to search log is useful, it is about ability to have an immediate idea from an error alone.

But it is up to you  - for any issue involving `500` most likely we will just transfer them to dandi-api anyways, so will be for dandi-api team to figure it out.  If you see no need - I will not force your hand, mark as `wontfix` and close. I am resting my case here.

**Comment by waxlamp** [comment]
> sure, but "can easily" is not exactly the answer to my specific question ("..what server side issue has caused that 500...?") and that is my point... it would take time to open the page, search for properly formatted date time (hopefully for the correct zone).
> 

To answer the question, here's the last frame of the stack trace that this example gave:

```
Feb 15 12:49:09 dandi-api app/web.1                     django.db.utils.DataError: value too long for               
Feb 15 12:49:09 dandi-api app/web.1                     type character varying(100)                                 
Feb 15 12:49:09 dandi-api app/web.1 10.30.238.92 - - [15/Feb/2021:20:49:09 +0000] "POST /api/uploads/validate/ HTTP/1.1" 500 145 "-" "python-requests/2.23.0"
```

(Note that the timestamp here is different--unfortunately, our papertrail plan makes the February 9th error log inaccessible, but this was the same error occurring a few days later.)

In this case, seeing the `DataError` referring to a too-long string being stored in the DB was the clue Daniel needed to fix the error, which was that our DB schema was not sufficient for storing a long filename.

> Not that ability to search log is useful, it is about ability to have an immediate idea from an error alone.
> 

When an error does occur, our development technique is indeed to dive into papertrail, find the full stack trace, and then diagnose the problem and come up with a fix. In this case, there really wasn't anything else we could have done beforehand to make the 500 error message more informative. The full information was contained in papertrail, but it truly wasn't a burden to open papertrail up, find the error, and continue from there.

> But it is up to you - for any issue involving `500` most likely we will just transfer them to dandi-api anyways, so will be for dandi-api team to figure it out. If you see no need - I will not force your hand, mark as `wontfix` and close. I am resting my case here.

Thanks for having this discussion. I do think the current cycle of using papertrail to diagnose "uncaught" errors is indeed effective, so I'll mark as wontfix and close. But of course any time you encounter a strange error, if you file an issue as you did here, we can track down the problem and improve the software in the course of fixing it.

**Comment by mgrauer** [comment]
I would amend this to say, for errors, go to sentry first, and then use papertrail to further investigate as needed, including adding additional diagnostic logging.
